Add translated readme file
mgba-emu/mgba pull request #2234
Opened 2021-07-03 19:58 UTC by Felipefpl

Added a brazilian portuguese translation of the readme file which was missing.

2021-07-03 22:50 UTC, endrift commented
cc @yuriks to review whenever you have time

2021-08-16 21:09 UTC, Felipefpl commented
Is there any problem with my pull or all the others? it's been more than one month and no answer for them.

2021-08-20 23:10 UTC, endrift commented
I was hoping to get @yuriks, who also know Brazilian Portuguese to give this a look over before it's merged. She had some comments on previous translations you'd contributed so I was hoping to get her to look at it when she had time.

2021-08-21 14:36 UTC, Felipefpl commented
> I was hoping to get @yuriks, who also know Brazilian Portuguese to give this a look over before it's merged.

Is she brazilian or just some person who has some knowledge of brazilian portuguese?

2021-08-21 16:17 UTC, yuriks commented
I'm Brazilian. Either way, the reason I've left this sitting is that I lost whatever motivation I had to review translations because of the churn in the UI translations. Months ago I had spent a significant amount of time reviewing older translation PRs and checking messages in the context of the UI to make sure that they made sense, as well as trying to figure out good replacements for terms which have no direct translation, and it was pretty frustrating to get another batch of updates that seemingly arbitrarily shuffled the wording of most of the UI again with no clear rationales behind it, and even re-introducing some of the context errors I'd pointed out when reviewing the initial translations. So I decided to skip on reviewing the previous PR and ended up not really having motivation to review this when it got submitted either, and ended up forgetting about it after putting it off.

The readme isn't super long so I'll just quickly cross-check this within the next few hours and ack if it looks good, sorry for the delays.

2021-08-22 20:12 UTC, yuriks requested changes
Sorry, this ended up taking longer than I expected so I couldn't finish it yesterday.

I left correction suggestions. I thought that the tone of some of the word choices in the original text tended to be too informal for documentation.

Also, why is the formatting in HTML? The original and all other translations are in Markdown format. This should probably be fixed unless there's a particular reason for it. (I don't really understand why you went through the trouble of converting it in the first place?)

Let me know if you disagree with any of the suggestions. I rarely write documents in Portuguese these days but I used references to try to make sure my grammar suggestions were correct at least.

2021-08-22 20:12 UTC, yuriks commented on README_PT_BR.md
> +<li><a href="http://www.7-zip.org/sdk.html">SDK do LZMA</a>, a qual é de domínio público.</li>
```suggestion
<li><a href="http://www.7-zip.org/sdk.html">SDK do LZMA</a>, o qual está sob o domínio público.</li>
```

2021-08-22 20:12 UTC, yuriks commented on README_PT_BR.md
> +<li><a href="https://github.com/aappleby/smhasher">MurmurHash3</a> implementação do Austin Appleby, a qual é de domínio público.</li>
```suggestion
<li>Implementação da <a href="https://github.com/aappleby/smhasher">MurmurHash3</a> por Austin Appleby, a qual está sob o domínio público.</li>
```

2021-08-22 20:12 UTC, yuriks commented on README_PT_BR.md
> +<li><a href="https://github.com/skandhurkat/Getopt-for-Visual-Studio/">getopt pro MSVC</a>, a qual é de domínio público.</li>
```suggestion
<li><a href="https://github.com/skandhurkat/Getopt-for-Visual-Studio/">getopt pro MSVC</a>, a qual está sob domínio público.</li>
```

2021-08-22 20:12 UTC, yuriks commented on README_PT_BR.md
> +<li><a href="https://www.sqlite.org">SQLite3</a>, a qual é de domínio público.</li>
```suggestion
<li><a href="https://www.sqlite.org">SQLite3</a>, a qual está sob o domínio público.</li>
```

2021-08-22 20:12 UTC, yuriks commented on README_PT_BR.md
> +<p>Se você é um publicador de jogos e desejar licenciar o mGBA pra uso comercial por favor envie um email pra <a href="mailto:licensing@mgba.io">licensing@mgba.io</a> pra mais informações.</p>
```suggestion
<p>Se você é um publicador de jogos e desejar licenciar o mGBA para uso comercial por favor envie um email para <a href="mailto:licensing@mgba.io">licensing@mgba.io</a> para mais informações.</p>
```

2021-08-22 20:12 UTC, yuriks commented on README_PT_BR.md
> +<li>9 slots pra savestates. Os savestates são também visíveis como screenshots.</li>
```suggestion
<li>9 slots para savestates. Os savestates são também visíveis como screenshots.</li>
```

2021-08-22 20:12 UTC, yuriks commented on README_PT_BR.md
> +<p>Os requerimentos são mínimos. Qualquer computador que consiga executar o Windows Vista ou mais novo deve ser capaz de lidar com a emulação. Suporte pra OpenGL 1.1 ou mais novo também é requerido,
```suggestion
<p>Os requerimentos são mínimos. Qualquer computador que consiga executar o Windows Vista ou mais novo deve ser capaz de lidar com a emulação. Suporte para OpenGL 1.1 ou mais novo também é requerido, com o OpenGL 3.2 ou mais novo para os shaders e funções avançadas.</p>
```

2021-08-22 20:46 UTC, Felipefpl commented
Well, i dont agree with those since the litteral translation doesnt make anyone from our land to misunderstand anything written, i'll close this and keep the translation stored to distribute someday.

2021-08-22 20:46 UTC, closed without merging