Add shortcut to disable all cheats
mgba-emu/mgba pull request #2897
Opened 2023-04-25 06:13 UTC by martinmurtiono

This adds a button/shortcut to disable all cheats

https://github.com/mgba-emu/mgba/issues/1352

^ I am part of Tam's group in our virtualization class.

2023-04-25 06:34 UTC, endrift requested changes
Looks mostly fine, minus some nitpicks. However, I do worry that this cheats window won't notice that they've been disabled under them. Did you test that?

2023-04-25 06:34 UTC, endrift commented on src/platform/qt/Window.cpp
> +	addGameAction(tr("&Disable cheats..."), "disableCheats", [this]() {
```suggestion
	addGameAction(tr("Disable all cheats"), "disableCheats", [this]() {
```

The "..." at the end indicates that it opens a new window, which this one doesn't.

2023-04-25 06:34 UTC, endrift commented on src/core/cheats.c
> +	return;
```suggestion
```

This line does nothing, so it should be removed.

2023-04-25 06:41 UTC, martinmurtiono commented
Yes, the checkboxes get unticked for all cheats in the window.

2023-04-26 08:22 UTC, endrift commented
Though the original request by @cibomatto2002 was to "disable" cheats I'm unsure if he meant "turn the cheats individually off" (as was done here) or "temporarily disable the cheat subsystem entirely in a way that means if you re-enable it you don't have to manually re-enable the individual cheats you want enabled", and I would assume the latter would be more useful. Perhaps he could chime in.

2023-04-26 08:44 UTC, martinmurtiono commented
That's a good point. I might as well just make it a toggle as its more useful that way.

2023-04-26 13:54 UTC, Cibomatto2002 commented
What I really wanted was a hot key to turn them all off at the same time it would be easier for the person that had a cheat on like infinite time.

2023-04-26 21:02 UTC, martinmurtiono commented
The current implementation turns all the cheats off like you described, but it might be more useful if it was a toggle to turn the cheats on/off. In that case, you can simply just press it once to disable all cheats, and for people who want an easy way to re-enable them, they have the option to repress the key and turn the cheats they previously had back on.

2023-04-26 22:30 UTC, endrift commented
Wanting to just mark all cheats as disabled instead of a "temporarily pause the cheat subsystem" is an incredibly niche use case and I don't think it's worthwhile. I'm going to close this PR until you get a version that adds the whole subsystem toggle.

2023-04-26 22:30 UTC, closed without merging

2023-04-26 23:38 UTC, martinmurtiono commented
I'm not getting what you mean by "temporarily pause the cheat subsystem". Does saving the currently enabled cheats when disabling them then re-enabling the same cheats when you toggle cheats back on achieve this? Or did you have another method in mind?

2023-04-27 01:18 UTC, martinmurtiono commented
@endrift  When you mean the whole subsystem, do you mean to temporarily disable the cheat window and any cheats that were enabled? I feel like we can achieve the same function by toggling the most recently enabled cheats on/off. In this case Cibomatto2002 can still have his desired functionality of simply disabling all the cheats, and when you toggle it back on, the most recently enabled cheats will be re-enabled so users don't have to individually re-enable them, and the cheat window will still be available to edit.