Added the `disass-style` command to the debugger
mgba-emu/mgba pull request #2907
Opened 2023-04-28 01:35 UTC by qwetboy10

The command will set the disassembler to either output decimal or hex representations of immediates. This is to make disassembly more clear so you don't have to convert values in a different tool. The command works on both ARM and sm83 code. This commit was originally made to solve #2553. Unfortunately that issue was actually invalid. However I already had the functionality of changing between decimal and hex for immediates implemented, so I added a command that would control it.

2023-04-28 02:24 UTC, endrift commented
First off: your editor appears to use soft tabs. Please use hard tabs to avoid causing reindentation issues.

Second: please use `disasm-style` instead of `disass-style`.

2023-04-29 07:32 UTC, endrift requested changes
Should be good to merge after fixing these 3 issues.

2023-04-29 07:32 UTC, endrift commented on include/mgba/internal/arm/decoder.h
> +#include <mgba/debugger/debugger.h>
```suggestion
#include <mgba/debugger/debugger.h>
#include <mgba/internal/arm/arm.h>
```

Keep these in alphabetical order.

2023-04-29 07:32 UTC, endrift commented on src/arm/decoder.c
> +	default:
You can combine this default with the case label above.

2023-04-29 07:32 UTC, endrift commented on src/sm83/decoder.c
> +				written = snprintf(buffer, blen, "$%03i", pc + (int8_t) op.immediate);
The $ indicates hexadecimal instead of 0x in SM83 assembly. Use no prefix for decimal and only $ for hexadecimal.

2023-05-03 01:14 UTC, endrift requested changes
More nits, sorry.

2023-05-03 01:14 UTC, endrift commented on src/sm83/decoder.c
> +			if(disassemblyStyle == DISASSEMBLY_STYLE_HEX) {
```suggestion
			if (disassemblyStyle == DISASSEMBLY_STYLE_HEX) {
```

2023-05-03 01:14 UTC, endrift commented on src/arm/decoder.c
> +	switch(disassemblyStyle) {
```suggestion
	switch (disassemblyStyle) {
```

Also, I meant having both the default and explicit cases separately listed, but it should probably be done with an if/else like you have in the SM83 implementation.

2023-05-03 01:14 UTC, endrift commented on src/sm83/decoder.c
> +				written = snprintf(buffer, blen, "%05i", pc + (int8_t) op.immediate);
```suggestion
				written = snprintf(buffer, blen, "%i", pc + (int8_t) op.immediate);
```

2023-05-03 01:14 UTC, endrift commented on src/sm83/decoder.c
> +				written = snprintf(buffer, blen, "%03i", pc + (int8_t) op.immediate);
```suggestion
				written = snprintf(buffer, blen, "%i", pc + (int8_t) op.immediate);
```

2023-05-04 08:51 UTC, avsnr requested changes

2023-05-04 08:51 UTC, avsnr commented on src/debugger/cli-debugger.c
>  #ifdef ENABLE_SCRIPTING
Ok

2023-06-05 10:33 UTC, endrift commented
Any updates on this PR?

2023-06-27 02:31 UTC, closed without merging