Load recent script
mgba-emu/mgba pull request #3266
Opened 2024-07-29 21:25 UTC by anthonydo8196

Finishing up #2845

Added your recommended changes on Tam's commits. 

I believe the reason why we originally stored the most recently used script separately was because we noticed that if you loaded a script when you went on the Load recent script menu, it wouldn't update the mru list. But I believe I fixed that by calling appendMRU again in updateMRU. Not sure if I needed to add an if but I did just to be safe so that it would only call appendMRU if the file was successfully loaded.

Also should the name for button be something other than Load recent? It shares the same words as Load recent script

![scriptingmenu](https://github.com/user-attachments/assets/aaaffc06-d049-45e8-89b6-b433707f7c9e)

2024-08-19 02:49 UTC, endrift requested changes
Some minor nits. Looks good otherwise.

2024-08-19 02:49 UTC, endrift commented on src/platform/qt/scripting/ScriptingView.cpp
> +	connect(m_ui.loadRecent, &QAction::triggered, this, &ScriptingView::loadRecent);
You should make sure this is disabled if the MRU is empty.

2024-08-19 02:49 UTC, endrift commented on src/platform/qt/scripting/ScriptingView.ui
> +    <string>&amp;Load recent</string>
The name is a bit confusing. Perhaps "Load most recent"?

2024-08-19 02:49 UTC, endrift commented on src/platform/qt/scripting/ScriptingView.cpp
> +			if(m_controller->loadFile(fname)) {
```suggestion
			if (m_controller->loadFile(fname)) {
```

I had wondered why this didn't work, but didn't look into it. Thanks for fixing that!

2024-08-20 01:45 UTC, anthonydo8196 commented
Added all the changes.  

It looks like this when the MRU list is empty. 
![loadActionDisabled](https://github.com/user-attachments/assets/2330e498-d5ce-4112-a8ad-d8524b4d660a)
Then once the user adds a script the action gets enabled and works properly.

2024-08-20 01:58 UTC, endrift approved these changes
Looks good, pending that one change.

2024-08-20 01:58 UTC, endrift commented on src/platform/qt/scripting/ScriptingView.cpp
> +	}
```suggestion
	m_ui.loadMostRecent->setEnabled(!m_mruFiles.isEmpty());
```

2024-08-20 01:58 UTC, merged

2024-08-20 05:29 UTC, anthonydo8196 commented on src/platform/qt/scripting/ScriptingView.cpp
> +	}
Ah that is much simpler  and cleaner.